name: Docker Image CI

on:
  - push

env:
  ALI_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMG_REPO: bxwill
  IMG_NAME: allure

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Login Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          echo "${{ secrets.ALI_DC_PASSWORD }}" | docker login -u ${{ secrets.ALI_DC_USER }} --password-stdin ${ALI_REGISTRY}
      - name: Build the Docker image
        run: |
          git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')
          docker build . --file Dockerfile --tag ${IMG_REPO}/${IMG_NAME}:${git_ref_name}
          docker tag ${IMG_REPO}/${IMG_NAME}:${git_ref_name} ${ALI_REGISTRY}/${IMG_REPO}/${IMG_NAME}:${git_ref_name}
      - name: Push the Docker image
        run: |
          git_ref_name=$(echo "${{ github.ref }}" | awk -F '/' '{print $NF}')
          docker push ${IMG_REPO}/${IMG_NAME}:${git_ref_name}
          docker push ${ALI_REGISTRY}/${IMG_REPO}/${IMG_NAME}:${git_ref_name}

